run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  # deprecated
  - maligned
  - nosnakecase
  - structcheck
  - golint
  - ifshort
  - scopelint
  - varcheck
  - deadcode
  - interfacer
  #############
  - exhaustivestruct
  - exhaustruct
  - depguard
  - musttag